import Foundation

extension Preferences {
  enum Key {
    static let version = "kBAUserDefaultsVersion"
    static let displayNextPrayer = "kBAUserDefaultsDisplayNextPrayer"
    static let displayNextPrayerType = "kBAUserDefaultsDisplayNextPrayerType"
    static let displayNextPrayerName = "kBAUserDefaultsDisplayNextPrayerName"
    static let displayIcon = "kBAUserDefaultsDisplayIcon"
    static let autoLocation = "kBAUserDefaultsAutoLocation"
    static let city = "kBAUserDefaultsLocationCity"
    static let state = "kBAUserDefaultsLocationState"
    static let country = "kBAUserDefaultsLocationCountry"
    static let countryName = "kBAUserDefaultsLocationCountryName"
    static let latitude = "kBAUserDefaultsLatitude"
    static let longitude = "kBAUserDefaultsLongitude"
    static let timeZone = "kBAUserDefaultsTimeZone"
    static let madhab = "kBAUserDefaultsMadhab"
    static let method = "kBAUserDefaultsMethod"
    static let highLatitudeRule = "kBAUserDefaultsHighLatitudeRule"
    static let autoDetectMethod = "kBAUserDefaultsAutoDetectMethod"
    static let autoDetectHighLatitudeRule = "kBAUserDefaultsAutoDetectHighLatitudeRule"
    static let customFajrAngle = "kBAUserDefaultsCustomFajrAngle"
    static let customIshaAngle = "kBAUserDefaultsCustomIshaAngle"
    static let adjustmentFajr = "kBAUserDefaultsAdjustmentFajr"
    static let adjustmentShuruq = "kBAUserDefaultsAdjustmentShuruq"
    static let adjustmentDhuhr = "kBAUserDefaultsAdjustmentDhuhr"
    static let adjustmentAsr = "kBAUserDefaultsAdjustmentAsr"
    static let adjustmentMaghrib = "kBAUserDefaultsAdjustmentMaghrib"
    static let adjustmentIsha = "kBAUserDefaultsAdjustmentIsha"
    static let hijriOffset = "kBAUserDefaultsHijriOffset"
    static let delayedIshaInRamadan = "kBAUserDefaultsDelayedIshaInRamadan"
    static let fajrReminderEnabled = "kBAUserDefaultsAlertFajrReminderEnabled"
    static let fajrAlertEnabled = "kBAUserDefaultsAlertFajrEnabled"
    static let shuruqReminderEnabled = "kBAUserDefaultsAlertShuruqReminderEnabled"
    static let shuruqAlertEnabled = "kBAUserDefaultsAlertShuruqEnabled"
    static let dhuhrAlertEnabled = "kBAUserDefaultsAlertDhuhrEnabled"
    static let asrAlertEnabled = "kBAUserDefaultsAlertAsrEnabled"
    static let maghribAlertEnabled = "kBAUserDefaultsAlertMaghribEnabled"
    static let ishaAlertEnabled = "kBAUserDefaultsAlertIshaEnabled"
    static let fajrAlertSound = "kBAUserDefaultsAlertFajrSound"
    static let dhuhrAlertSound = "kBAUserDefaultsAlertDhuhrSound"
    static let asrAlertSound = "kBAUserDefaultsAlertAsrSound"
    static let maghribAlertSound = "kBAUserDefaultsAlertMaghribSound"
    static let ishaAlertSound = "kBAUserDefaultsAlertIshaSound"
    static let fajrCustomSound = "kBAUserDefaultsAlertFajrCustomSound"
    static let dhuhrCustomSound = "kBAUserDefaultsAlertDhuhrCustomSound"
    static let asrCustomSound = "kBAUserDefaultsAlertAsrCustomSound"
    static let maghribCustomSound = "kBAUserDefaultsAlertMaghribCustomSound"
    static let ishaCustomSound = "kBAUserDefaultsAlertIshaCustomSound"
    static let alertVolume = "kBAUserDefaultsAlertVolume"
    static let duaEnabled = "kBAUserDefaultsDua"
    static let silentMode = "kBAUserDefaultsSilentMode"
    static let fajrReminderOffset = "kBAUserDefaultsAlertFajrReminderOffset"
    static let shuruqReminderOffset = "kBAUserDefaultsAlertShuruqReminderOffset"
    static let notificationSettings = "kBANotificationSettings"
    static let jumuahOverrideEnabled = "kBAUserDefaultsJumuahOverrideEnabled"
    static let appLanguage = "kBAUserDefaultsAppLanguage"
    // Widget appearance (theming)
    static let widgetThemeID = "kBAUserDefaultsWidgetThemeID"
    static let widgetCustomAccent = "kBAUserDefaultsWidgetCustomAccent"
    static let widgetCustomPrimary = "kBAUserDefaultsWidgetCustomPrimary"
    static let widgetCustomBase = "kBAUserDefaultsWidgetCustomBase"
    static let widgetAppearance = "kBAUserDefaultsWidgetAppearance"
  }
}
